apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
    app: myjavaapppppppp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjavaapppppppp
  template:
    metadata:
      labels:
        app: myjavaapppppppp
    spec:
      containers:
      - name: myjavaapp-container
        image: abbbinash/myapp21nov:1
        ports:
        - containerPort: 8080