apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
    app: myfirstapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myfirstapp
  template:
    metadata:
      labels:
        app: myfirstapp
    spec:
      containers:
      - name: myjavaapp-container
        image: abbbinash/myfirstapp:2
        ports:
        - containerPort: 8080