apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 2
  selector:
    app: javaappppppppppppp 
    version: 2.6.1
  template:
    metadata:
      labels:
        app: javaappppppppppppp 
        version: 2.6.1
    spec:
      containers:
        - name: mycontainer
          image: maha4iac/mahalogin:1
          ports:
            - containerPort: 8080
