apiVersion: apps/v1
kind: Service
metadata: 
    name: maha-svc
    labels:  
      app: javaappppppppppppp 
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodeport: 30001
    portocol: TCP
  selecter: 
    app: javaappppppppppppp     
