apiVersion: v1
kind: Service
metadata: 
  name: my-svc
  labels: 
    app:  javaappppppppppppp
spec: 
  type: NodePort
  ports:
  - port: 8080
    nodeport: 30001
    protocol: TCP
  selecter: 
   app: javaappppppppppppp
