apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: myjavaapppppppp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: myjavaapppppppp
    